# Generated by Django 3.1.5 on 2021-06-21 20:35

import app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', app.fields.LowercaseCharField(max_length=40)),
                ('type', models.CharField(choices=[('subj', 'Subject'), ('obj', 'Object'), ('pos_det', 'Possessive determiner'), ('pos_pro', 'Possessive pronoun'), ('reflex', 'Reflexive')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='PronounSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=60)),
                ('pronouns', models.ManyToManyField(to='app.Pronoun')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('pronoun_series', models.ManyToManyField(to='app.PronounSeries')),
            ],
        ),
    ]
