# Generated by Django 3.1.5 on 2021-06-22 17:32

import app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('new_attributes', models.JSONField(blank=True, default=dict, null=True)),
                ('text', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('word_count', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('tokenized_text', models.JSONField(blank=True, default=None, null=True)),
                ('word_counts_counter', models.JSONField(blank=True, default=dict, null=True)),
                ('part_of_speech_tags', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', app.fields.LowercaseCharField(max_length=40)),
                ('type', models.CharField(choices=[('subj', 'Subject'), ('obj', 'Object'), ('pos_det', 'Possessive determiner'), ('pos_pro', 'Possessive pronoun'), ('reflex', 'Reflexive')], max_length=7)),
            ],
        ),
    ]
