# Generated by Django 3.1.5 on 2021-06-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210623_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='word_counts_counter',
            new_name='word_count_counter',
        ),
    ]
