# Generated by Django 3.1.5 on 2021-06-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210623_1831'),
        ('app', '0003_pronounseries_gender_models'),
    ]

    operations = [
    ]
