# Generated by Django 3.1.5 on 2021-06-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210623_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
