# Generated by Django 3.1.5 on 2021-06-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_pronounseries_pronouns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='names_series',
        ),
    ]
