# Generated by Django 3.1.5 on 2021-07-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='corpora',
            field=models.ManyToManyField(to='app.Corpus'),
        ),
    ]
