# Generated by Django 3.1.5 on 2021-07-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('documents', models.ManyToManyField(to='app.Document')),
            ],
            options={
                'verbose_name_plural': 'Corpora',
            },
        ),
    ]
