# Generated by Django 3.1.5 on 2021-06-23 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_gender_names_series'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pronoun',
        ),
    ]
