# Generated by Django 3.1.5 on 2021-07-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_corpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='documents',
            field=models.ManyToManyField(blank=True, to='app.Document'),
        ),
    ]
