# Generated by Django 3.1.5 on 2021-07-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_corpus'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField()),
                ('by_date', models.JSONField()),
                ('by_document', models.JSONField()),
                ('by_gender', models.JSONField()),
                ('by_metadata', models.JSONField()),
                ('by_overlap', models.JSONField()),
            ],
        ),
    ]
