# Generated by Django 3.1.5 on 2021-07-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210709_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name_plural': 'Corpora'},
        ),
    ]
