# Generated by Django 3.1.5 on 2021-07-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210712_1847'),
        ('app', '0008_proximity-analyses'),
    ]

    operations = [
    ]
