# Generated by Django 3.1.5 on 2021-06-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_pronoun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameseries',
            name='names',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='NameSeries',
        ),
    ]
