# Generated by Django 3.1.5 on 2021-07-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210712_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProximityAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')
                 ),
                ('word_window', models.PositiveIntegerField()),
                ('results', models.JSONField()),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='proximity_analyses',
                                             to='app.corpus')
                 ),
                ('genders', models.ManyToManyField(related_name='proximity_analyses', to='app.Gender')),
            ],
            options={
                'verbose_name_plural': 'proximity analyses',
            },
        ),
    ]
