# Generated by Django 3.1.5 on 2021-07-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='alias_dict',
        ),
        migrations.RemoveField(
            model_name='document',
            name='character_dict',
        ),
        migrations.RemoveField(
            model_name='document',
            name='cleaned_text',
        ),
        migrations.AddField(
            model_name='alias',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alias',
            name='coref_clusters',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='mentions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alias',
            name='new_attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='part_of_speech_tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alias',
            name='tokenized_text',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='word_count_counter',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='aliases',
            field=models.ManyToManyField(to='app.Alias'),
        ),
        migrations.AddField(
            model_name='document',
            name='aliases',
            field=models.ManyToManyField(to='app.Alias'),
        ),
        migrations.AddField(
            model_name='document',
            name='characters',
            field=models.ManyToManyField(to='app.Character'),
        ),
    ]
