# Generated by Django 3.1.5 on 2021-07-20 14:57

from django.db import migrations


def modify_db_seed(apps, schema):
    """
    Resolves the pos_det/pos_pro mix-up with the `PronounSeries` constants defined in migration 0006.
    """
    PronounSeries = apps.get_model('app', 'PronounSeries')

    for she_series in PronounSeries.objects.filter(identifier='Fem'):
        she_series.pos_det = 'her'
        she_series.pos_pro = 'hers'
        she_series.save()

    for they_series in PronounSeries.objects.filter(identifier='Andy'):
        they_series.pos_det = 'their'
        they_series.pos_pro = 'theirs'
        they_series.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0008_auto_20210712_1847'),
    ]

    operations = [
        migrations.RunPython(code=modify_db_seed, reverse_code=migrations.RunPython.noop)
    ]
