# Generated by Django 3.1.5 on 2021-06-24 03:48

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_name_nameseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronounseries',
            name='obj',
            field=app.fields.LowercaseCharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pronounseries',
            name='pos_det',
            field=app.fields.LowercaseCharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pronounseries',
            name='pos_pro',
            field=app.fields.LowercaseCharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pronounseries',
            name='reflex',
            field=app.fields.LowercaseCharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pronounseries',
            name='subj',
            field=app.fields.LowercaseCharField(max_length=40),
        ),
    ]
