# Generated by Django 3.1.5 on 2021-07-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_modify_initial_data'),
        ('app', '0009_proximity_analysis'),
    ]

    operations = [
    ]
