# Generated by Django 3.1.5 on 2021-06-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210623_1831'),
        ('app', '0010_pronounseries_fields_blank_false'),
    ]

    operations = [
    ]
