# Generated by Django 3.1.5 on 2021-07-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_proximity_db_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField()),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_analyses', to='app.corpus')),
                ('genders', models.ManyToManyField(related_name='frequency_analyses', to='app.Gender')),
            ],
            options={
                'verbose_name_plural': 'Frequency Analyses',
            },
        ),
    ]
