# Generated by Django 3.1.5 on 2021-11-22 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_frequencyanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistinctivenessAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField()),
                ('corpus_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_analysis_corpora_1', to='app.corpus')),
                ('corpus_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_analysis_corpora_2', to='app.corpus')),
            ],
            options={
                'verbose_name_plural': 'Distinctiveness Analyses',
            },
        ),
    ]
