# Generated by Django 3.1.5 on 2021-07-15 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_character_common_name'),
        ('app', '0007_corpus'),
    ]

    operations = [
    ]
