# Generated by Django 3.1.5 on 2021-11-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_distinctivenessanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinctivenessanalysis',
            name='corpus_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_analyses_for_corpus_1', to='app.corpus'),
        ),
        migrations.AlterField(
            model_name='distinctivenessanalysis',
            name='corpus_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_analyses_for_corpus_2', to='app.corpus'),
        ),
    ]
