# Generated by Django 3.1.5 on 2021-07-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20210714_2159'),
        ('app', '0009_modify_initial_data'),
    ]

    operations = [
    ]
